#! /bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# gets path of file being executed
DIR=$(dirname $(readlink -e $0))

# adds vars file to ~/.zshrc on line 49
log_daemon_msg "adding up variables ..."
if sed -i "s#plugins=(git)#\#plugins=(git)\nsource $DIR/vars#" ~/.zshrc;
    then log_end_msg 0 else log_end_msg 1
fi

# addes path to .zshrc script to users /.zshrc
log_daemon_msg "Setting up ~/.zshrc ..."
if echo "source $DIR/zshrc" >> ~/.zshrc;
    then log_end_msg 0 else log_end_msg 1
fi

log_daemon_msg "Adding global aliases"
if sudo sh -c 'cat $DIR/global-aliases >> /etc/zsh/zshrc';
    then log_end_msg 0 else log_end_msg 1
fi

# Aliases and functions will now be able to be used
log_daemon_msg "rehashing"
if SHELL;
    then log_end_msg 0 else log_end_msg 1
fi

exit 0
